apiVersion: v1
kind: Service
metadata:
  name: api-web
spec:
  type: NodePort
  selector:
    app: api-web
  ports:
  - name: http-api
    port: 8080
    targetPort: 8080
    nodePort: 30012
  - name: http-web
    port: 8081
    targetPort: 8081
    nodePort: 30013
---
apiVersion: v1
kind: Pod
metadata:
  name: api-web
  labels:
    app: api-web
spec:
  containers:
  - name: api
    image: commojun/socialpoll-api:0.1.4
    ports:
    - containerPort: 8080
    envFrom:
    - secretRef:
        name: socialpoll
  - name: web
    image: commojun/socialpoll-web:0.1.8
    ports:
    - containerPort: 8081
    envFrom:
    - secretRef:
        name: socialpoll
