apiVersion: v1
kind: Pod
metadata:
  name: counter
  labels:
    app: counter
spec:
  containers:
  - name: counter
    image: commojun/socialpoll-counter:0.1.4
    envFrom:
    - secretRef:
        name: socialpoll
