apiVersion: v1
kind: Service
metadata:
  name: nsqlookupd
spec:
  selector:
    app: nsqlookupd
  ports:
  - name: http1
    port: 4160
  - name: http2
    port: 4161
---
apiVersion: v1
kind: Pod
metadata:
  name: nsqlookupd
  labels:
    app: nsqlookupd
spec:
  containers:
  - name: nsqlookupd
    image: commojun/nsqlookupd:0.1.4
    ports:
    - containerPort: 4160
    - containerPort: 4161
    envFrom:
    - secretRef:
        name: socialpoll
